### ISSUE TITLE
New column options for CRMGridView a bit unstable

### ISSUE THREAD

**Issue by rappen** [jamesnovak/xrmtb.XrmToolBox.Controls#10]
Changes from #8 are slightly unstable, at first retrieval it shows no columns, and null value columns never show friendly names.
See snippet: https://www.screencast.com/t/HLqbRVzLFOr
Ping @MarkMpn 😊

**Comment by rappen** [comment]
And after changing the query, it still (first time executing) still includes attributes from the previous query...
![image](https://user-images.githubusercontent.com/2572253/81325766-226a2880-9099-11ea-9d01-10b74872057a.png)

**Comment by rappen** [comment]
Showing null value columns also shows id column:
https://www.screencast.com/t/nlgdInnLnp2Z

**Comment by MarkMpn** [comment]
The friendly name logic depends on values being present as the column may be aliased or from a link entity, and the entity collection doesn't provide this metadata except where it is populated, so I don't think this is possible to fill in without requiring the caller to supply the extra information.

I've tried to reproduce the other errors in the control tester plugin without success. Can you reproduce them there?

**Comment by rappen** [comment]
Re: Friendly - I think this continue is the problem. 
https://github.com/jamesnovak/xrmtb.XrmToolBox.Controls/blob/master/XrmToolBox.Controls/Controls/CRMGridView.cs#L622-L625

Perhaps don't continue if we're on the very last record, sort of as a last resort go grab the proper metadata anyway, even if it will fail for aliased columns?

**Comment by rappen** [comment]
Re: Reproducing the rest - can you try to repro with the latest bits of FXB? 😉
The things you see in my clips is there, only the two new properties (w/o value and system added) are commented out for now. Updating to latest packages will make them possible to uncomment.
See changes in https://github.com/rappen/FetchXMLBuilder/commit/895512bd9af22301f6fb78a62f09f7a07250aee2 if you want to have a go.

**Comment by MarkMpn** [comment]
I've merged it with my changes in https://github.com/rappen/FetchXMLBuilder/pull/291 and it seems to work as expected. Can you try with these changes and see if you can still reproduce it?
